// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: gbmj.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cmd 是 Envelope.cmd。C2S 为客户端请求，S2C 为服务器推送/回包。
type Cmd int32

const (
	Cmd_CMD_UNSPECIFIED Cmd = 0
	Cmd_C2S_AUTH        Cmd = 1
	Cmd_S2C_AUTH        Cmd = 2
	Cmd_C2S_CHAT        Cmd = 10
	Cmd_S2C_CHAT        Cmd = 11
	Cmd_C2S_FRIEND_ASK  Cmd = 20
	Cmd_C2S_FRIEND_RESP Cmd = 21
	Cmd_C2S_FRIEND_LIST Cmd = 22
	Cmd_S2C_FRIEND_SYNC Cmd = 23
	Cmd_C2S_ROOM_CREATE Cmd = 40
	Cmd_C2S_ROOM_JOIN   Cmd = 41
	Cmd_C2S_ROOM_SIT    Cmd = 42
	Cmd_C2S_ROOM_KICK   Cmd = 43
	Cmd_C2S_ROOM_INVITE Cmd = 44
	Cmd_C2S_ROOM_START  Cmd = 45
	Cmd_C2S_ROOM_LEAVE  Cmd = 47
	Cmd_C2S_ROOM_READY  Cmd = 48
	Cmd_S2C_ROOM_STATE  Cmd = 46
	Cmd_C2S_ACTION      Cmd = 80
	Cmd_S2C_GAME_EVENT  Cmd = 81
	Cmd_S2C_DEAL        Cmd = 82
	Cmd_S2C_SETTLE      Cmd = 83
	Cmd_S2C_ERROR       Cmd = 90
)

// Enum value maps for Cmd.
var (
	Cmd_name = map[int32]string{
		0:  "CMD_UNSPECIFIED",
		1:  "C2S_AUTH",
		2:  "S2C_AUTH",
		10: "C2S_CHAT",
		11: "S2C_CHAT",
		20: "C2S_FRIEND_ASK",
		21: "C2S_FRIEND_RESP",
		22: "C2S_FRIEND_LIST",
		23: "S2C_FRIEND_SYNC",
		40: "C2S_ROOM_CREATE",
		41: "C2S_ROOM_JOIN",
		42: "C2S_ROOM_SIT",
		43: "C2S_ROOM_KICK",
		44: "C2S_ROOM_INVITE",
		45: "C2S_ROOM_START",
		47: "C2S_ROOM_LEAVE",
		48: "C2S_ROOM_READY",
		46: "S2C_ROOM_STATE",
		80: "C2S_ACTION",
		81: "S2C_GAME_EVENT",
		82: "S2C_DEAL",
		83: "S2C_SETTLE",
		90: "S2C_ERROR",
	}
	Cmd_value = map[string]int32{
		"CMD_UNSPECIFIED": 0,
		"C2S_AUTH":        1,
		"S2C_AUTH":        2,
		"C2S_CHAT":        10,
		"S2C_CHAT":        11,
		"C2S_FRIEND_ASK":  20,
		"C2S_FRIEND_RESP": 21,
		"C2S_FRIEND_LIST": 22,
		"S2C_FRIEND_SYNC": 23,
		"C2S_ROOM_CREATE": 40,
		"C2S_ROOM_JOIN":   41,
		"C2S_ROOM_SIT":    42,
		"C2S_ROOM_KICK":   43,
		"C2S_ROOM_INVITE": 44,
		"C2S_ROOM_START":  45,
		"C2S_ROOM_LEAVE":  47,
		"C2S_ROOM_READY":  48,
		"S2C_ROOM_STATE":  46,
		"C2S_ACTION":      80,
		"S2C_GAME_EVENT":  81,
		"S2C_DEAL":        82,
		"S2C_SETTLE":      83,
		"S2C_ERROR":       90,
	}
)

func (x Cmd) Enum() *Cmd {
	p := new(Cmd)
	*p = x
	return p
}

func (x Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_gbmj_proto_enumTypes[0].Descriptor()
}

func (Cmd) Type() protoreflect.EnumType {
	return &file_gbmj_proto_enumTypes[0]
}

func (x Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd.Descriptor instead.
func (Cmd) EnumDescriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{0}
}

type Code int32

const (
	Code_CODE_OK           Code = 0
	Code_CODE_AUTH_FAIL    Code = 1
	Code_CODE_RATE_LIMITED Code = 2
	Code_CODE_PERM_DENIED  Code = 3
	Code_CODE_NOT_FOUND    Code = 4
	Code_CODE_BAD_STATE    Code = 5
	Code_CODE_BAD_ACTION   Code = 6
	Code_CODE_ROOM_FULL    Code = 7
	Code_CODE_DUP          Code = 8
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "CODE_OK",
		1: "CODE_AUTH_FAIL",
		2: "CODE_RATE_LIMITED",
		3: "CODE_PERM_DENIED",
		4: "CODE_NOT_FOUND",
		5: "CODE_BAD_STATE",
		6: "CODE_BAD_ACTION",
		7: "CODE_ROOM_FULL",
		8: "CODE_DUP",
	}
	Code_value = map[string]int32{
		"CODE_OK":           0,
		"CODE_AUTH_FAIL":    1,
		"CODE_RATE_LIMITED": 2,
		"CODE_PERM_DENIED":  3,
		"CODE_NOT_FOUND":    4,
		"CODE_BAD_STATE":    5,
		"CODE_BAD_ACTION":   6,
		"CODE_ROOM_FULL":    7,
		"CODE_DUP":          8,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_gbmj_proto_enumTypes[1].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_gbmj_proto_enumTypes[1]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{1}
}

type ActionType int32

const (
	ActionType_ACT_UNSPECIFIED ActionType = 0
	ActionType_ACT_PASS        ActionType = 1
	ActionType_ACT_DISCARD     ActionType = 2
	ActionType_ACT_CHI         ActionType = 3
	ActionType_ACT_PENG        ActionType = 4
	ActionType_ACT_GANG_MING   ActionType = 5
	ActionType_ACT_GANG_AN     ActionType = 6
	ActionType_ACT_GANG_JIA    ActionType = 7
	ActionType_ACT_HU          ActionType = 8
	ActionType_ACT_DRAW        ActionType = 9
	ActionType_ACT_BUHUA       ActionType = 10
	ActionType_ACT_READY       ActionType = 11
	ActionType_ACT_SIT         ActionType = 12
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0:  "ACT_UNSPECIFIED",
		1:  "ACT_PASS",
		2:  "ACT_DISCARD",
		3:  "ACT_CHI",
		4:  "ACT_PENG",
		5:  "ACT_GANG_MING",
		6:  "ACT_GANG_AN",
		7:  "ACT_GANG_JIA",
		8:  "ACT_HU",
		9:  "ACT_DRAW",
		10: "ACT_BUHUA",
		11: "ACT_READY",
		12: "ACT_SIT",
	}
	ActionType_value = map[string]int32{
		"ACT_UNSPECIFIED": 0,
		"ACT_PASS":        1,
		"ACT_DISCARD":     2,
		"ACT_CHI":         3,
		"ACT_PENG":        4,
		"ACT_GANG_MING":   5,
		"ACT_GANG_AN":     6,
		"ACT_GANG_JIA":    7,
		"ACT_HU":          8,
		"ACT_DRAW":        9,
		"ACT_BUHUA":       10,
		"ACT_READY":       11,
		"ACT_SIT":         12,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_gbmj_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_gbmj_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{2}
}

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq  uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Cmd  Cmd    `protobuf:"varint,2,opt,name=cmd,proto3,enum=gbmj.Cmd" json:"cmd,omitempty"`
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Code int32  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetCmd() Cmd {
	if x != nil {
		return x.Cmd
	}
	return Cmd_CMD_UNSPECIFIED
}

func (x *Envelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type C2SAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *C2SAuth) Reset() {
	*x = C2SAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuth) ProtoMessage() {}

func (x *C2SAuth) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuth.ProtoReflect.Descriptor instead.
func (*C2SAuth) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{1}
}

func (x *C2SAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type S2CAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *S2CAuth) Reset() {
	*x = S2CAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuth) ProtoMessage() {}

func (x *S2CAuth) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuth.ProtoReflect.Descriptor instead.
func (*S2CAuth) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{2}
}

func (x *S2CAuth) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *S2CAuth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type C2SChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text []byte `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *C2SChat) Reset() {
	*x = C2SChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChat) ProtoMessage() {}

func (x *C2SChat) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChat.ProtoReflect.Descriptor instead.
func (*C2SChat) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{3}
}

func (x *C2SChat) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

type S2CChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Text []byte `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *S2CChat) Reset() {
	*x = S2CChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChat) ProtoMessage() {}

func (x *S2CChat) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChat.ProtoReflect.Descriptor instead.
func (*S2CChat) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{4}
}

func (x *S2CChat) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *S2CChat) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

type C2SFriendAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer int64 `protobuf:"varint,1,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *C2SFriendAsk) Reset() {
	*x = C2SFriendAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SFriendAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SFriendAsk) ProtoMessage() {}

func (x *C2SFriendAsk) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SFriendAsk.ProtoReflect.Descriptor instead.
func (*C2SFriendAsk) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{5}
}

func (x *C2SFriendAsk) GetPeer() int64 {
	if x != nil {
		return x.Peer
	}
	return 0
}

type C2SFriendResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer   int64 `protobuf:"varint,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Accept bool  `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
}

func (x *C2SFriendResp) Reset() {
	*x = C2SFriendResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SFriendResp) ProtoMessage() {}

func (x *C2SFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SFriendResp.ProtoReflect.Descriptor instead.
func (*C2SFriendResp) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{6}
}

func (x *C2SFriendResp) GetPeer() int64 {
	if x != nil {
		return x.Peer
	}
	return 0
}

func (x *C2SFriendResp) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type FriendItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Online bool   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *FriendItem) Reset() {
	*x = FriendItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendItem) ProtoMessage() {}

func (x *FriendItem) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendItem.ProtoReflect.Descriptor instead.
func (*FriendItem) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{7}
}

func (x *FriendItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FriendItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FriendItem) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type S2CFriendSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*FriendItem `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Pending []*FriendItem `protobuf:"bytes,2,rep,name=pending,proto3" json:"pending,omitempty"`
}

func (x *S2CFriendSync) Reset() {
	*x = S2CFriendSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CFriendSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CFriendSync) ProtoMessage() {}

func (x *S2CFriendSync) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CFriendSync.ProtoReflect.Descriptor instead.
func (*S2CFriendSync) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{8}
}

func (x *S2CFriendSync) GetFriends() []*FriendItem {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *S2CFriendSync) GetPending() []*FriendItem {
	if x != nil {
		return x.Pending
	}
	return nil
}

type C2SRoomCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TurnSec  uint32 `protobuf:"varint,1,opt,name=turn_sec,json=turnSec,proto3" json:"turn_sec,omitempty"`    // 每回合免费决策秒数，0=服务器默认 10
	ExtraSec uint32 `protobuf:"varint,2,opt,name=extra_sec,json=extraSec,proto3" json:"extra_sec,omitempty"` // 每人整局储备秒数，0=服务器默认 20
}

func (x *C2SRoomCreate) Reset() {
	*x = C2SRoomCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomCreate) ProtoMessage() {}

func (x *C2SRoomCreate) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomCreate.ProtoReflect.Descriptor instead.
func (*C2SRoomCreate) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{9}
}

func (x *C2SRoomCreate) GetTurnSec() uint32 {
	if x != nil {
		return x.TurnSec
	}
	return 0
}

func (x *C2SRoomCreate) GetExtraSec() uint32 {
	if x != nil {
		return x.ExtraSec
	}
	return 0
}

type C2SRoomJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *C2SRoomJoin) Reset() {
	*x = C2SRoomJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomJoin) ProtoMessage() {}

func (x *C2SRoomJoin) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomJoin.ProtoReflect.Descriptor instead.
func (*C2SRoomJoin) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{10}
}

func (x *C2SRoomJoin) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type C2SRoomSit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat uint32 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
}

func (x *C2SRoomSit) Reset() {
	*x = C2SRoomSit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomSit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomSit) ProtoMessage() {}

func (x *C2SRoomSit) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomSit.ProtoReflect.Descriptor instead.
func (*C2SRoomSit) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{11}
}

func (x *C2SRoomSit) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

type C2SRoomKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *C2SRoomKick) Reset() {
	*x = C2SRoomKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomKick) ProtoMessage() {}

func (x *C2SRoomKick) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomKick.ProtoReflect.Descriptor instead.
func (*C2SRoomKick) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{12}
}

func (x *C2SRoomKick) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type C2SRoomInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *C2SRoomInvite) Reset() {
	*x = C2SRoomInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomInvite) ProtoMessage() {}

func (x *C2SRoomInvite) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomInvite.ProtoReflect.Descriptor instead.
func (*C2SRoomInvite) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{13}
}

func (x *C2SRoomInvite) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type C2SRoomStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SRoomStart) Reset() {
	*x = C2SRoomStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomStart) ProtoMessage() {}

func (x *C2SRoomStart) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomStart.ProtoReflect.Descriptor instead.
func (*C2SRoomStart) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{14}
}

type C2SRoomLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SRoomLeave) Reset() {
	*x = C2SRoomLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomLeave) ProtoMessage() {}

func (x *C2SRoomLeave) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomLeave.ProtoReflect.Descriptor instead.
func (*C2SRoomLeave) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{15}
}

type C2SRoomReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *C2SRoomReady) Reset() {
	*x = C2SRoomReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomReady) ProtoMessage() {}

func (x *C2SRoomReady) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomReady.ProtoReflect.Descriptor instead.
func (*C2SRoomReady) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{16}
}

func (x *C2SRoomReady) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type SeatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ready  bool   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	Online bool   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *SeatInfo) Reset() {
	*x = SeatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatInfo) ProtoMessage() {}

func (x *SeatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatInfo.ProtoReflect.Descriptor instead.
func (*SeatInfo) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{17}
}

func (x *SeatInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SeatInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeatInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *SeatInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type S2CRoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     string      `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Owner      int64       `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Seats      []*SeatInfo `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	Phase      uint32      `protobuf:"varint,4,opt,name=phase,proto3" json:"phase,omitempty"`
	InviteHint string      `protobuf:"bytes,5,opt,name=invite_hint,json=inviteHint,proto3" json:"invite_hint,omitempty"`
	TurnSec    uint32      `protobuf:"varint,6,opt,name=turn_sec,json=turnSec,proto3" json:"turn_sec,omitempty"`    // 本房每回合免费秒数
	ExtraSec   uint32      `protobuf:"varint,7,opt,name=extra_sec,json=extraSec,proto3" json:"extra_sec,omitempty"` // 本房每人整局储备秒数
}

func (x *S2CRoomState) Reset() {
	*x = S2CRoomState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRoomState) ProtoMessage() {}

func (x *S2CRoomState) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRoomState.ProtoReflect.Descriptor instead.
func (*S2CRoomState) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{18}
}

func (x *S2CRoomState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2CRoomState) GetOwner() int64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *S2CRoomState) GetSeats() []*SeatInfo {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *S2CRoomState) GetPhase() uint32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *S2CRoomState) GetInviteHint() string {
	if x != nil {
		return x.InviteHint
	}
	return ""
}

func (x *S2CRoomState) GetTurnSec() uint32 {
	if x != nil {
		return x.TurnSec
	}
	return 0
}

func (x *S2CRoomState) GetExtraSec() uint32 {
	if x != nil {
		return x.ExtraSec
	}
	return 0
}

type C2SAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TurnId uint32     `protobuf:"varint,1,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Type   ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=gbmj.ActionType" json:"type,omitempty"`
	Tile   uint32     `protobuf:"varint,3,opt,name=tile,proto3" json:"tile,omitempty"`
	ChiMid uint32     `protobuf:"varint,4,opt,name=chi_mid,json=chiMid,proto3" json:"chi_mid,omitempty"`
}

func (x *C2SAction) Reset() {
	*x = C2SAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAction) ProtoMessage() {}

func (x *C2SAction) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAction.ProtoReflect.Descriptor instead.
func (*C2SAction) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{19}
}

func (x *C2SAction) GetTurnId() uint32 {
	if x != nil {
		return x.TurnId
	}
	return 0
}

func (x *C2SAction) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACT_UNSPECIFIED
}

func (x *C2SAction) GetTile() uint32 {
	if x != nil {
		return x.Tile
	}
	return 0
}

func (x *C2SAction) GetChiMid() uint32 {
	if x != nil {
		return x.ChiMid
	}
	return 0
}

type S2CGameEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TurnId      uint32     `protobuf:"varint,1,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Type        ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=gbmj.ActionType" json:"type,omitempty"`
	Seat        uint32     `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`
	Tile        uint32     `protobuf:"varint,4,opt,name=tile,proto3" json:"tile,omitempty"`
	Tiles       []byte     `protobuf:"bytes,5,opt,name=tiles,proto3" json:"tiles,omitempty"`
	WallLeft    uint32     `protobuf:"varint,6,opt,name=wall_left,json=wallLeft,proto3" json:"wall_left,omitempty"`
	Mask        uint32     `protobuf:"varint,7,opt,name=mask,proto3" json:"mask,omitempty"`
	WaitMs      uint32     `protobuf:"varint,8,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`                         // 你这一步距被代打/代过还剩多少毫秒
	ExtraLeftMs []uint32   `protobuf:"varint,9,rep,packed,name=extra_left_ms,json=extraLeftMs,proto3" json:"extra_left_ms,omitempty"` // 固定 4 个，各座位剩余储备毫秒
	TurnMs      uint32     `protobuf:"varint,10,opt,name=turn_ms,json=turnMs,proto3" json:"turn_ms,omitempty"`                        // 每回合免费决策毫秒，默认 10000
}

func (x *S2CGameEvent) Reset() {
	*x = S2CGameEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGameEvent) ProtoMessage() {}

func (x *S2CGameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGameEvent.ProtoReflect.Descriptor instead.
func (*S2CGameEvent) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{20}
}

func (x *S2CGameEvent) GetTurnId() uint32 {
	if x != nil {
		return x.TurnId
	}
	return 0
}

func (x *S2CGameEvent) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACT_UNSPECIFIED
}

func (x *S2CGameEvent) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *S2CGameEvent) GetTile() uint32 {
	if x != nil {
		return x.Tile
	}
	return 0
}

func (x *S2CGameEvent) GetTiles() []byte {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *S2CGameEvent) GetWallLeft() uint32 {
	if x != nil {
		return x.WallLeft
	}
	return 0
}

func (x *S2CGameEvent) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

func (x *S2CGameEvent) GetWaitMs() uint32 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *S2CGameEvent) GetExtraLeftMs() []uint32 {
	if x != nil {
		return x.ExtraLeftMs
	}
	return nil
}

func (x *S2CGameEvent) GetTurnMs() uint32 {
	if x != nil {
		return x.TurnMs
	}
	return 0
}

type S2CDeal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat        uint32   `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Hand        []byte   `protobuf:"bytes,2,opt,name=hand,proto3" json:"hand,omitempty"`
	Banker      uint32   `protobuf:"varint,3,opt,name=banker,proto3" json:"banker,omitempty"`
	Wind        uint32   `protobuf:"varint,4,opt,name=wind,proto3" json:"wind,omitempty"`
	TurnId      uint32   `protobuf:"varint,5,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	WaitMs      uint32   `protobuf:"varint,6,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	ExtraLeftMs []uint32 `protobuf:"varint,7,rep,packed,name=extra_left_ms,json=extraLeftMs,proto3" json:"extra_left_ms,omitempty"`
	TurnMs      uint32   `protobuf:"varint,8,opt,name=turn_ms,json=turnMs,proto3" json:"turn_ms,omitempty"`
}

func (x *S2CDeal) Reset() {
	*x = S2CDeal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDeal) ProtoMessage() {}

func (x *S2CDeal) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDeal.ProtoReflect.Descriptor instead.
func (*S2CDeal) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{21}
}

func (x *S2CDeal) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *S2CDeal) GetHand() []byte {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *S2CDeal) GetBanker() uint32 {
	if x != nil {
		return x.Banker
	}
	return 0
}

func (x *S2CDeal) GetWind() uint32 {
	if x != nil {
		return x.Wind
	}
	return 0
}

func (x *S2CDeal) GetTurnId() uint32 {
	if x != nil {
		return x.TurnId
	}
	return 0
}

func (x *S2CDeal) GetWaitMs() uint32 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *S2CDeal) GetExtraLeftMs() []uint32 {
	if x != nil {
		return x.ExtraLeftMs
	}
	return nil
}

func (x *S2CDeal) GetTurnMs() uint32 {
	if x != nil {
		return x.TurnMs
	}
	return 0
}

type FanItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score uint32 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *FanItem) Reset() {
	*x = FanItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FanItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanItem) ProtoMessage() {}

func (x *FanItem) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanItem.ProtoReflect.Descriptor instead.
func (*FanItem) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{22}
}

func (x *FanItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FanItem) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type S2CSettle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Winner    uint32     `protobuf:"varint,1,opt,name=winner,proto3" json:"winner,omitempty"`
	HuKind    int32      `protobuf:"varint,2,opt,name=hu_kind,json=huKind,proto3" json:"hu_kind,omitempty"` // 0荒庄 1自摸 2点炮 3抢杠 4错和
	Fan       int32      `protobuf:"varint,3,opt,name=fan,proto3" json:"fan,omitempty"`
	Fans      []*FanItem `protobuf:"bytes,4,rep,name=fans,proto3" json:"fans,omitempty"`
	Scores    []int32    `protobuf:"varint,5,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	Hands     []byte     `protobuf:"bytes,6,opt,name=hands,proto3" json:"hands,omitempty"`
	Discarder uint32     `protobuf:"varint,7,opt,name=discarder,proto3" json:"discarder,omitempty"`
}

func (x *S2CSettle) Reset() {
	*x = S2CSettle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbmj_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CSettle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSettle) ProtoMessage() {}

func (x *S2CSettle) ProtoReflect() protoreflect.Message {
	mi := &file_gbmj_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSettle.ProtoReflect.Descriptor instead.
func (*S2CSettle) Descriptor() ([]byte, []int) {
	return file_gbmj_proto_rawDescGZIP(), []int{23}
}

func (x *S2CSettle) GetWinner() uint32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *S2CSettle) GetHuKind() int32 {
	if x != nil {
		return x.HuKind
	}
	return 0
}

func (x *S2CSettle) GetFan() int32 {
	if x != nil {
		return x.Fan
	}
	return 0
}

func (x *S2CSettle) GetFans() []*FanItem {
	if x != nil {
		return x.Fans
	}
	return nil
}

func (x *S2CSettle) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *S2CSettle) GetHands() []byte {
	if x != nil {
		return x.Hands
	}
	return nil
}

func (x *S2CSettle) GetDiscarder() uint32 {
	if x != nil {
		return x.Discarder
	}
	return 0
}

var File_gbmj_proto protoreflect.FileDescriptor

var file_gbmj_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x62, 0x6d, 0x6a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x62,
	0x6d, 0x6a, 0x22, 0x61, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71,
	0x12, 0x1b, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e,
	0x67, 0x62, 0x6d, 0x6a, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x43, 0x32, 0x53, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2f, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x41, 0x75, 0x74,
	0x68, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x43, 0x32, 0x53, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2f, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x43, 0x68, 0x61,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x41, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0d, 0x43,
	0x32, 0x53, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x22, 0x4a, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x22, 0x67, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2a, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x62, 0x6d, 0x6a, 0x2e, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x62, 0x6d, 0x6a, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x47, 0x0a,
	0x0d, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x65, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x53, 0x65, 0x63, 0x22, 0x26, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f,
	0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x20,
	0x0a, 0x0a, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74,
	0x22, 0x1f, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f, 0x6d, 0x4b, 0x69, 0x63, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0x21, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f, 0x6d, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x22, 0x5e, 0x0a, 0x08, 0x53, 0x65,
	0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x0c, 0x53,
	0x32, 0x43, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x65,
	0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x62, 0x6d, 0x6a,
	0x2e, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x73, 0x65, 0x61, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x5f,
	0x73, 0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x75, 0x72, 0x6e, 0x53,
	0x65, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x63, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x65, 0x78, 0x74, 0x72, 0x61, 0x53, 0x65, 0x63, 0x22,
	0x77, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x75, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74,
	0x75, 0x72, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x62, 0x6d, 0x6a, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6c, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x68, 0x69, 0x5f, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x63, 0x68, 0x69, 0x4d, 0x69, 0x64, 0x22, 0x92, 0x02, 0x0a, 0x0c, 0x53, 0x32, 0x43,
	0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x75, 0x72,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x75, 0x72, 0x6e,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x67, 0x62, 0x6d, 0x6a, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x5f, 0x6c,
	0x65, 0x66, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x4c,
	0x65, 0x66, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x61, 0x69, 0x74, 0x5f,
	0x6d, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x61, 0x69, 0x74, 0x4d, 0x73,
	0x12, 0x22, 0x0a, 0x0d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x6d,
	0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x72, 0x61, 0x4c, 0x65,
	0x66, 0x74, 0x4d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x6d, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x22, 0xcc, 0x01,
	0x0a, 0x07, 0x53, 0x32, 0x43, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x6e,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x69, 0x6e,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x74, 0x75, 0x72, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x6d,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x61, 0x69, 0x74, 0x4d, 0x73, 0x12,
	0x22, 0x0a, 0x0d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x6d, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x72, 0x61, 0x4c, 0x65, 0x66,
	0x74, 0x4d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x22, 0x2f, 0x0a, 0x07,
	0x46, 0x61, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0xbd, 0x01,
	0x0a, 0x09, 0x53, 0x32, 0x43, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x75, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x75, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x66, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x66, 0x61, 0x6e, 0x12, 0x21,
	0x0a, 0x04, 0x66, 0x61, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67,
	0x62, 0x6d, 0x6a, 0x2e, 0x46, 0x61, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x66, 0x61, 0x6e,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61, 0x6e,
	0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2a, 0xa8, 0x03,
	0x0a, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x32,
	0x53, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f,
	0x41, 0x55, 0x54, 0x48, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x48,
	0x41, 0x54, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x48, 0x41, 0x54,
	0x10, 0x0b, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x5f, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44,
	0x5f, 0x41, 0x53, 0x4b, 0x10, 0x14, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f, 0x46, 0x52,
	0x49, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x15, 0x12, 0x13, 0x0a, 0x0f, 0x43,
	0x32, 0x53, 0x5f, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x16,
	0x12, 0x13, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x5f, 0x53,
	0x59, 0x4e, 0x43, 0x10, 0x17, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x4f, 0x4f,
	0x4d, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x28, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x32,
	0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x29, 0x12, 0x10, 0x0a,
	0x0c, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x49, 0x54, 0x10, 0x2a, 0x12,
	0x11, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4b, 0x49, 0x43, 0x4b,
	0x10, 0x2b, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x49,
	0x4e, 0x56, 0x49, 0x54, 0x45, 0x10, 0x2c, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x5f, 0x52,
	0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x2d, 0x12, 0x12, 0x0a, 0x0e, 0x43,
	0x32, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x2f, 0x12,
	0x12, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x10, 0x30, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x2e, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x50, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x51, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x32, 0x43, 0x5f, 0x44, 0x45, 0x41, 0x4c, 0x10, 0x52, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x32, 0x43,
	0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x10, 0x53, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x32, 0x43,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x5a, 0x2a, 0xb3, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x41, 0x54, 0x45, 0x5f,
	0x4c, 0x49, 0x4d, 0x49, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x50, 0x45, 0x52, 0x4d, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x42, 0x41, 0x44, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x44, 0x45, 0x5f,
	0x42, 0x41, 0x44, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x07,
	0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x55, 0x50, 0x10, 0x08, 0x2a, 0xd6,
	0x01, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a,
	0x0f, 0x41, 0x43, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x54, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x43, 0x54, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x41, 0x52, 0x44, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x43, 0x54, 0x5f, 0x43, 0x48, 0x49, 0x10, 0x03, 0x12, 0x0c,
	0x0a, 0x08, 0x41, 0x43, 0x54, 0x5f, 0x50, 0x45, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d,
	0x41, 0x43, 0x54, 0x5f, 0x47, 0x41, 0x4e, 0x47, 0x5f, 0x4d, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12,
	0x0f, 0x0a, 0x0b, 0x41, 0x43, 0x54, 0x5f, 0x47, 0x41, 0x4e, 0x47, 0x5f, 0x41, 0x4e, 0x10, 0x06,
	0x12, 0x10, 0x0a, 0x0c, 0x41, 0x43, 0x54, 0x5f, 0x47, 0x41, 0x4e, 0x47, 0x5f, 0x4a, 0x49, 0x41,
	0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x5f, 0x48, 0x55, 0x10, 0x08, 0x12, 0x0c,
	0x0a, 0x08, 0x41, 0x43, 0x54, 0x5f, 0x44, 0x52, 0x41, 0x57, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09,
	0x41, 0x43, 0x54, 0x5f, 0x42, 0x55, 0x48, 0x55, 0x41, 0x10, 0x0a, 0x12, 0x0d, 0x0a, 0x09, 0x41,
	0x43, 0x54, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x0b, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x43,
	0x54, 0x5f, 0x53, 0x49, 0x54, 0x10, 0x0c, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x69, 0x79, 0x61, 0x6e, 0x67, 0x6b, 0x61, 0x6f,
	0x72, 0x6f, 0x75, 0x2d, 0x62, 0x6f, 0x6f, 0x70, 0x2f, 0x47, 0x42, 0x5f, 0x6d, 0x61, 0x68, 0x6a,
	0x6f, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gbmj_proto_rawDescOnce sync.Once
	file_gbmj_proto_rawDescData = file_gbmj_proto_rawDesc
)

func file_gbmj_proto_rawDescGZIP() []byte {
	file_gbmj_proto_rawDescOnce.Do(func() {
		file_gbmj_proto_rawDescData = protoimpl.X.CompressGZIP(file_gbmj_proto_rawDescData)
	})
	return file_gbmj_proto_rawDescData
}

var file_gbmj_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gbmj_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_gbmj_proto_goTypes = []interface{}{
	(Cmd)(0),              // 0: gbmj.Cmd
	(Code)(0),             // 1: gbmj.Code
	(ActionType)(0),       // 2: gbmj.ActionType
	(*Envelope)(nil),      // 3: gbmj.Envelope
	(*C2SAuth)(nil),       // 4: gbmj.C2SAuth
	(*S2CAuth)(nil),       // 5: gbmj.S2CAuth
	(*C2SChat)(nil),       // 6: gbmj.C2SChat
	(*S2CChat)(nil),       // 7: gbmj.S2CChat
	(*C2SFriendAsk)(nil),  // 8: gbmj.C2SFriendAsk
	(*C2SFriendResp)(nil), // 9: gbmj.C2SFriendResp
	(*FriendItem)(nil),    // 10: gbmj.FriendItem
	(*S2CFriendSync)(nil), // 11: gbmj.S2CFriendSync
	(*C2SRoomCreate)(nil), // 12: gbmj.C2SRoomCreate
	(*C2SRoomJoin)(nil),   // 13: gbmj.C2SRoomJoin
	(*C2SRoomSit)(nil),    // 14: gbmj.C2SRoomSit
	(*C2SRoomKick)(nil),   // 15: gbmj.C2SRoomKick
	(*C2SRoomInvite)(nil), // 16: gbmj.C2SRoomInvite
	(*C2SRoomStart)(nil),  // 17: gbmj.C2SRoomStart
	(*C2SRoomLeave)(nil),  // 18: gbmj.C2SRoomLeave
	(*C2SRoomReady)(nil),  // 19: gbmj.C2SRoomReady
	(*SeatInfo)(nil),      // 20: gbmj.SeatInfo
	(*S2CRoomState)(nil),  // 21: gbmj.S2CRoomState
	(*C2SAction)(nil),     // 22: gbmj.C2SAction
	(*S2CGameEvent)(nil),  // 23: gbmj.S2CGameEvent
	(*S2CDeal)(nil),       // 24: gbmj.S2CDeal
	(*FanItem)(nil),       // 25: gbmj.FanItem
	(*S2CSettle)(nil),     // 26: gbmj.S2CSettle
}
var file_gbmj_proto_depIdxs = []int32{
	0,  // 0: gbmj.Envelope.cmd:type_name -> gbmj.Cmd
	10, // 1: gbmj.S2CFriendSync.friends:type_name -> gbmj.FriendItem
	10, // 2: gbmj.S2CFriendSync.pending:type_name -> gbmj.FriendItem
	20, // 3: gbmj.S2CRoomState.seats:type_name -> gbmj.SeatInfo
	2,  // 4: gbmj.C2SAction.type:type_name -> gbmj.ActionType
	2,  // 5: gbmj.S2CGameEvent.type:type_name -> gbmj.ActionType
	25, // 6: gbmj.S2CSettle.fans:type_name -> gbmj.FanItem
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_gbmj_proto_init() }
func file_gbmj_proto_init() {
	if File_gbmj_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gbmj_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SFriendAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SFriendResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CFriendSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomSit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRoomState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGameEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CDeal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FanItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbmj_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CSettle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gbmj_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gbmj_proto_goTypes,
		DependencyIndexes: file_gbmj_proto_depIdxs,
		EnumInfos:         file_gbmj_proto_enumTypes,
		MessageInfos:      file_gbmj_proto_msgTypes,
	}.Build()
	File_gbmj_proto = out.File
	file_gbmj_proto_rawDesc = nil
	file_gbmj_proto_goTypes = nil
	file_gbmj_proto_depIdxs = nil
}
